name: Build Docker Image

on:
  workflow_run:
    workflows: ["Build JAR"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download JAR
        uses: actions/download-artifact@v5
        with:
          name: bigkart-jar
          path: target

      - name: Build Docker image
        run: docker build -t bigkart:latest .
